services:
  events-db:
    image: postgres:17
    container_name: event-postgres
    environment:
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpassword
      POSTGRES_DB: eventsDB
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U eventuser" ]
      interval: 5s
      timeout: 5s
      retries: 5

  events-service:
    image: events-service:dev
    container_name: event-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAVEN_PROFILE: development
    ports:
      - "8080:8080"
    depends_on:
      events-db:
        condition: service_healthy