services:
  events-db:
    image: postgres:17
    container_name: event-postgres
    environment:
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpassword
      POSTGRES_DB: eventsDB
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U eventuser" ]
      interval: 5s
      timeout: 5s
      retries: 5

  events-service:
    image: events-service:dev
    container_name: event-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAVEN_PROFILE: development
    ports:
      - "8080:8080"
    depends_on:
      events-db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    depends_on:
      - events-service

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      #- grafana-storage:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning

volumes:
  prometheus-data:
  grafana-storage: