name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build-test-deploy:
    env:
      TZ: America/Argentina/Buenos_Aires
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn clean verify --batch-mode -Ptest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/events-service

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Trigger deploy to Render
        env:
          TAG: ${{ github.ref_name }}
        run: |
          IMAGE_URL="docker.io/jerecalvet/events-service:${TAG}"
          ENCODED_IMAGE_URL=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$IMAGE_URL''', safe=''))")
          
          FINAL_URL="${DEPLOY_HOOK}&imgURL=${ENCODED_IMAGE_URL}"
          echo "Triggering Render deploy with image tag: $TAG"
          echo "Final URL: $FINAL_URL"
          curl -X POST "$FINAL_URL"

